#!/usr/bin/env bash
# bin/compile <build-dir> <cache-dir>

# fail fast
set -e

# debug
# set -x

# clean up leaking environment
unset GIT_DIR

# config
SYSSTAT_URL="https://lmp-heroku-buidlpacks.s3.amazonaws.com/sysstat/systat.tgz"

# parse and derive params
BUILD_DIR=$1
CACHE_DIR=$2

LP_DIR=`cd $(dirname $0); cd ..; pwd`
BUILDPACK_DIR="$(dirname $(dirname $0))"

echo "-----> Fetching sysstat into slug"
curl --progress-bar -o /tmp/sysstat.tgz $SYSSTAT_URL
tar -xvf "$BUILD_DIR/sysstat" /tmp/sysstat.tgz

#echo "-----> adding installer script into app/.profile.d"

#cleaning up...
rm -rf /tmp/sysstat*

echo "-----> sysstat installation done"
