#!/usr/bin/env bash
# bin/compile <build-dir> <cache-dir>

# fail fast
set -e

# debug
# set -x

# clean up leaking environment
unset GIT_DIR

# config
SYSSTAT_URL="https://lmp-heroku-buidlpacks/sysstat/systat.tgz

# parse and derive params
BUILD_DIR=$1
CACHE_DIR=$2

LP_DIR=`cd $(dirname $0); cd ..; pwd`
BUILDPACK_DIR="$(dirname $(dirname $0))"

echo "-----> Fetching sysstat into slug"
curl --progress-bar -o /tmp/sysstat.tgz $SYSSTAT_URL
unzip -qq -d "$BUILD_DIR/vendor" /tmp/awscli-bundle.zip

echo "-----> adding installer script into app/.profile.d"
mkdir -p $BUILD_DIR/.profile.d
cp "$BUILDPACK_DIR/bin/install_awscli.sh" $BUILD_DIR/.profile.d/
chmod +x $BUILD_DIR/.profile.d/install_awscli.sh

#cleaning up...
rm -rf /tmp/awscli*

echo "-----> sysstat installation done"
